MERGE INTO RAW.METADATA.DATA_REFRESHES AS T
USING (
    SELECT * FROM (
        SELECT
            ROOT_TASK_NAME,
            SPLIT_PART(ROOT_TASK_NAME,'_',2) AS TABLE_NAME,
            DATABASE_NAME,
            SCHEMA_NAME,
            COMPLETED_TIME, 
            STATE,
            RUN_ID,
            ROW_NUMBER() OVER (PARTITION BY ROOT_TASK_NAME
                ORDER BY GREATEST(
                        COMPLETED_TIME
                    ) DESC NULLS LAST)
            AS RN
        FROM TABLE(INFORMATION_SCHEMA.COMPLETE_TASK_GRAPHS())
        ) WHERE RN = 1 
            AND STATE = 'SUCCEEDED'
            AND DATABASE_NAME = 'RAW' 
            AND SCHEMA_NAME != 'METADATA'
    ) AS S
    ON T.ROOT_TASK_NAME = S.ROOT_TASK_NAME AND T.DATABASE_NAME = S.DATABASE_NAME AND T.SCHEMA_NAME = S.SCHEMA_NAME AND T.RUN_ID = S.RUN_ID
WHEN MATCHED AND NOT(
    EQUAL_NULL(T.LAST_UPDATED_TIME, S.COMPLETED_TIME)
) AND S.COMPLETED_TIME > T.LAST_UPDATED_TIME
THEN UPDATE SET
    T.LAST_UPDATED_TIME = S.COMPLETED_TIME
WHEN NOT MATCHED THEN INSERT (
    ROOT_TASK_NAME,
    RUN_ID,
    TABLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    LAST_UPDATED_TIME
) VALUES (
    ROOT_TASK_NAME,
    RUN_ID,
    TABLE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    COMPLETED_TIME
)
