BEGIN
    BEGIN TRANSACTION;
        DELETE FROM RAW.AIRTABLE.HANDBACK_LOG;

        INSERT INTO RAW.AIRTABLE.HANDBACK_LOG (
            ID,
            CREATED_TIME,
            SHIPMENT_NUMBER,
            HANDBACK_TYPE,
            CODE,
            SECONDARY_REASON_CODE_CARRIER,
            SECONDARY_REASON_CODE_SHIPPER,
            COMMENTS,
            CARRIER_NAME,
            CARRIER_NAME_LOOKUP,
            NOTIFICATION_DATE,
            ORIGINAL_COST,
            LOAD_TS
        ) SELECT
            VAR:id::VARCHAR AS ID,
            TO_TIMESTAMP_TZ(VAR:createdTime::VARCHAR) AS CREATED_TIME,
            VAR:SHIPMENT_NUMBER::VARCHAR AS SHIPMENT_NUMBER,
            VAR:HandbackType::VARCHAR AS HANDBACK_TYPE,
            VAR:CODE::VARCHAR AS CODE,
            VAR:SECONDARY_REASON_CODE_CARRIER::VARCHAR AS SECONDARY_REASON_CODE_CARRIER,
            VAR:SECONDARY_REASON_CODE_SHIPPER::VARCHAR AS SECONDARY_REASON_CODE_SHIPPER,
            VAR:COMMENTS::VARCHAR AS COMMENTS,
            VAR:CARRIER_NAME::VARCHAR AS CARRIER_NAME,
            VAR:CARRIER_NAME_LOOKUP::VARCHAR AS CARRIER_NAME_LOOKUP,
            TO_TIMESTAMP_TZ(VAR:NOTIFICATION_DATE::VARCHAR) AS NOTIFICATION_DATE,
            VAR:ORIGINAL_COST::VARCHAR AS ORIGINAL_COST,
            SYSDATE() AS LOAD_TS
        FROM RAW.AIRTABLE.LOAD_HANDBACK_LOG_STREAM;

    COMMIT;
END
