BEGIN
    BEGIN TRANSACTION;
        DELETE FROM RAW.AIRTABLE.VEHICLE_BANDING;

        INSERT INTO RAW.AIRTABLE.VEHICLE_BANDING (
            ID,
            CREATED_TIME,
            VEHICLE_BANDING_HBEFA,
            LOAD_TS
        ) SELECT
            VAR:id::VARCHAR AS ID,
            TO_TIMESTAMP_TZ(VAR:createdTime::VARCHAR) AS CREATED_TIME,
            VAR:"VehicleBanding(HBEFA)"::VARCHAR AS VEHICLE_BANDING_HBEFA,
            SYSDATE()
        FROM RAW.AIRTABLE.LOAD_VEHICLE_BANDING_STREAM;

    COMMIT;
END
