MERGE INTO RAW.CARBON_REPORT.CARBON_REPORT AS target
USING (
    SELECT 
        "NAME" as SHIPMENT_NUMBER,
        TOTAL_IMPACT_CLIMATE_CHANGE,
        IS_EXCLUDED,
        SHIPMENT_WEIGHT,
        TOTAL_TRAVELLED_DISTANCE_KM,
        ROAD_TRAVELLED_DISTANCE_KM,
        SEA_TRAVELLED_DISTANCE_KM,
        TRUCK_VEHICLE_TYPE,
        FERRY_VEHICLE_TYPE,
        FUEL_CONSUMPTION,
        LOAD_FACTOR,
        FUEL_CONVERSION_FACTOR,
        TRUCK_FUEL_TYPE,
        ENERGY_CONVERSION_FACTOR,
        TRUCK_MAX_CAPACITY,
        TRUCK_MIN_CAPACITY,
        SYSDATE() AS LOAD_TS
    FROM RAW.CARBON_REPORT.LOAD_CARBON_REPORT_STREAM
) AS source
ON (
    target.SHIPMENT_NUMBER = source.SHIPMENT_NUMBER
)
WHEN MATCHED THEN
    UPDATE SET
        target.TOTAL_IMPACT_CLIMATE_CHANGE = source.TOTAL_IMPACT_CLIMATE_CHANGE,
        target.IS_EXCLUDED = source.IS_EXCLUDED,
        target.SHIPMENT_WEIGHT = source.SHIPMENT_WEIGHT,
        target.TOTAL_TRAVELLED_DISTANCE_KM = source.TOTAL_TRAVELLED_DISTANCE_KM,
        target.ROAD_TRAVELLED_DISTANCE_KM = source.ROAD_TRAVELLED_DISTANCE_KM,
        target.SEA_TRAVELLED_DISTANCE_KM = source.SEA_TRAVELLED_DISTANCE_KM,
        target.TRUCK_VEHICLE_TYPE = source.TRUCK_VEHICLE_TYPE,
        target.FERRY_VEHICLE_TYPE = source.FERRY_VEHICLE_TYPE,
        target.FUEL_CONSUMPTION = source.FUEL_CONSUMPTION,
        target.LOAD_FACTOR = source.LOAD_FACTOR,
        target.FUEL_CONVERSION_FACTOR = source.FUEL_CONVERSION_FACTOR,
        target.TRUCK_FUEL_TYPE = source.TRUCK_FUEL_TYPE,
        target.ENERGY_CONVERSION_FACTOR = source.ENERGY_CONVERSION_FACTOR,
        target.TRUCK_MAX_CAPACITY = source.TRUCK_MAX_CAPACITY,
        target.TRUCK_MIN_CAPACITY = source.TRUCK_MIN_CAPACITY,
        target.LOAD_TS = source.LOAD_TS
WHEN NOT MATCHED THEN
    INSERT (
        SHIPMENT_NUMBER,
        TOTAL_IMPACT_CLIMATE_CHANGE,
        IS_EXCLUDED,
        SHIPMENT_WEIGHT,
        TOTAL_TRAVELLED_DISTANCE_KM,
        ROAD_TRAVELLED_DISTANCE_KM,
        SEA_TRAVELLED_DISTANCE_KM,
        TRUCK_VEHICLE_TYPE,
        FERRY_VEHICLE_TYPE,
        FUEL_CONSUMPTION,
        LOAD_FACTOR,
        FUEL_CONVERSION_FACTOR,
        TRUCK_FUEL_TYPE,
        ENERGY_CONVERSION_FACTOR,
        TRUCK_MAX_CAPACITY,
        TRUCK_MIN_CAPACITY,
        LOAD_TS
    ) VALUES (
        source.SHIPMENT_NUMBER,
        source.TOTAL_IMPACT_CLIMATE_CHANGE,
        source.IS_EXCLUDED,
        source.SHIPMENT_WEIGHT,
        source.TOTAL_TRAVELLED_DISTANCE_KM,
        source.ROAD_TRAVELLED_DISTANCE_KM,
        source.SEA_TRAVELLED_DISTANCE_KM,
        source.TRUCK_VEHICLE_TYPE,
        source.FERRY_VEHICLE_TYPE,
        source.FUEL_CONSUMPTION,
        source.LOAD_FACTOR,
        source.FUEL_CONVERSION_FACTOR,
        source.TRUCK_FUEL_TYPE,
        source.ENERGY_CONVERSION_FACTOR,
        source.TRUCK_MAX_CAPACITY,
        source.TRUCK_MIN_CAPACITY,
        source.LOAD_TS
    )
