BEGIN
    BEGIN TRANSACTION;
        
        DELETE FROM RAW.TARGET_BUY_RATES.TARGET_BUY_RATE_PROJECTS;

        INSERT INTO RAW.TARGET_BUY_RATES.TARGET_BUY_RATE_PROJECTS (
            PROJECT_NAME,
            RATE_TYPE,
            LOAD_TS
        ) 
        SELECT 
            PROJECT_NAME::VARCHAR,
            RATE_TYPE::VARCHAR,
            SYSDATE()
        FROM RAW.TARGET_BUY_RATES.LOAD_TARGET_BUY_RATE_PROJECTS_STREAM;

    COMMIT;
END
