CREATE SHARE PROD_RAW_SHARE;
ALTER SHARE PROD_RAW_SHARE ADD ACCOUNTS = nb72547;
GRANT USAGE ON DATABASE RAW TO SHARE PROD_RAW_SHARE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO SHARE PROD_RAW_SHARE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO SHARE PROD_RAW_SHARE;