USE ROLE ACCOUNTADMIN;
CREATE ROLE SHAREADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SHAREADMIN;
CREATE DATABASE PROD_RAW FROM SHARE CP23351.PROD_RAW_SHARE;
GRANT IMPORTED PRIVILEGES ON DATABASE PROD_RAW TO ROLE SHAREADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE PROD_RAW TO ROLE TRANSFORMER;
GRANT IMPORTED PRIVILEGES ON DATABASE PROD_RAW TO ROLE DEVELOPER;
GRANT ROLE SHAREADMIN TO ROLE LOADER;