CREATE OR REPLACE NOTIFICATION INTEGRATION AZ_ERROR_INTEGRATION
  ENABLED = true
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_EVENT_GRID
  DIRECTION = OUTBOUND 
  AZURE_EVENT_GRID_TOPIC_ENDPOINT = 'https://snowflake-errors-dhdp-prod.northeurope-1.eventgrid.azure.net/api/events'
  AZURE_TENANT_ID = '9a27c3d7-c6aa-4d6d-b8a0-712b8e9d1516';

GRANT USAGE ON INTEGRATION AZ_ERROR_INTEGRATION TO ROLE LOADER;