name: Deploy - PROD
on:
  push:
    branches:
      - main
    paths:
      - "migrations/**"

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}.${{ secrets.SNOWFLAKE_REGION }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
  SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
  SNOWFLAKE_PRIVATE_KEY_PATH: "/tmp/rsa.p8"
  PYTHON_VERSION: "3.10"

jobs:
  deploy-raw:
    name: "Apply Migrations (RAW)"
    runs-on: ubuntu-latest
    concurrency: sf_prod_environment
    environment: prod
        
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      
      - name: Add snowflake key as file
        run: echo "${{ env.SNOWFLAKE_PRIVATE_KEY }}" > $SNOWFLAKE_PRIVATE_KEY_PATH

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: pip install -r requirements.txt
      
      - name: Changed Files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34.4.4
        with:
          files: |
            migrations/raw/migrations/**/*.sql*

      - name: Run step if any file(s) in the migrations/raw folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the migrations/raw folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"

      - name: Lint SQL
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: sqlfluff lint ${{ steps.changed-files-specific.outputs.all_changed_files }}